spring:
  datasource:
    url: jdbc:postgresql://192.168.0.49:5432/umc
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true